using System;
using System.Collections.Generic;
using System.Threading;

namespace AbcTuneTool.FileIo {

    internal class EntityLookup {
        internal Dictionary<string, string> lookup = new Dictionary<string, string>(StringComparer.Ordinal);
        internal Dictionary<string, string> reverseLookup = new Dictionary<string, string>();
    }

    /// <summary>
    ///     entity utilities
    /// </summary>
    public static class Entities {

        private static void Add(EntityLookup result, string value, params string[] names) {
            foreach (var key in names) {
                var entity = string.Concat("&", key, ";");
                result.lookup[entity] = value;
                result.reverseLookup[value] = entity;
            }
        }

        private static readonly Lazy<EntityLookup> values = new Lazy<EntityLookup>(GetEntities, LazyThreadSafetyMode.PublicationOnly);

        // the following list was extracted from wikipedia
        // and is therefore licensed under cc-by-sa
        //
        // License text:
        // https://creativecommons.org/licenses/by-sa/3.0/
        //
        // Original source:
        // https://en.wikipedia.org/wiki/List_of_XML_and_HTML_character_entity_references
        // the list was modified and shortened to fit here


        private static EntityLookup GetEntities() {
            var result = new EntityLookup();
            Add(result, Environment.NewLine, "Newline");
            Add(result, "\t", "Tab");
            Add(result, "!", "excl");
            Add(result, "\"", "quot");
            Add(result, "#", "num");
            Add(result, "$", "dollar");
            Add(result, "%", "percnt");
            Add(result, "&", "amp");
            Add(result, "\'", "apos");
            Add(result, "(", "lpar");
            Add(result, ")", "rpar");
            Add(result, "*", "ast", "midast");
            Add(result, "+", "plus");
            Add(result, ",", "comma");
            Add(result, ".", "period");
            Add(result, "/", "sol");
            Add(result, ":", "colon");
            Add(result, ";", "semi");
            Add(result, "<", "lt", "LT");
            Add(result, "=", "equals");
            Add(result, ">", "gt", "GT");
            Add(result, "?", "quest");
            Add(result, "@", "commat");
            Add(result, "[", "lsqb", "lbrack");
            Add(result, "\\", "bsol");
            Add(result, "]", "rsqb", "rbrack");
            Add(result, "^", "Hat");
            Add(result, "_", "lowbar", "UnderBar");
            Add(result, "`", "grave", "DiacriticalGrave");
            Add(result, "{", "lcub", "lbrace");
            Add(result, "|", "verbar", "vert", "VerticalLine");
            Add(result, "}", "rcub", "rbrace");
            Add(result, " ", "nbsp", "NonBreakingSpace");
            Add(result, "¡", "iexcl");
            Add(result, "¢", "cent");
            Add(result, "£", "pound");
            Add(result, "¤", "curren");
            Add(result, "¥", "yen");
            Add(result, "¦", "brvbar");
            Add(result, "§", "sect");
            Add(result, "¨", "Dot", "die", "DoubleDot", "uml");
            Add(result, "©", "copy");
            Add(result, "ª", "ordf");
            Add(result, "«", "laquo");
            Add(result, "¬", "not");
            Add(result, "­", "shy");
            Add(result, "®", "reg", "circledR");
            Add(result, "¯", "macr", "strns");
            Add(result, "°", "deg");
            Add(result, "±", "plusmn", "pm", "PlusMinus");
            Add(result, "²", "sup2");
            Add(result, "³", "sup3");
            Add(result, "´", "acute", "DiacriticalAcute");
            Add(result, "µ", "micro");
            Add(result, "¶", "para");
            Add(result, "·", "middot", "centerdot");
            Add(result, "¸", "cedil", "Cedilla");
            Add(result, "¹", "sup1");
            Add(result, "º", "ordm");
            Add(result, "»", "raquo");
            Add(result, "¼", "frac14");
            Add(result, "½", "frac12", "half");
            Add(result, "¾", "frac34");
            Add(result, "¿", "iquest");
            Add(result, "À", "Agrave");
            Add(result, "Á", "Aacute");
            Add(result, "Â", "Acirc");
            Add(result, "Ã", "Atilde");
            Add(result, "Ä", "Auml");
            Add(result, "Å", "Aring", "angst");
            Add(result, "Æ", "AElig");
            Add(result, "Ç", "Ccedil");
            Add(result, "È", "Egrave");
            Add(result, "É", "Eacute");
            Add(result, "Ê", "Ecirc");
            Add(result, "Ë", "Euml");
            Add(result, "Ì", "Igrave");
            Add(result, "Í", "Iacute");
            Add(result, "Î", "Icirc");
            Add(result, "Ï", "Iuml");
            Add(result, "Ð", "ETH");
            Add(result, "Ñ", "Ntilde");
            Add(result, "Ò", "Ograve");
            Add(result, "Ó", "Oacute");
            Add(result, "Ô", "Ocirc");
            Add(result, "Õ", "Otilde");
            Add(result, "Ö", "Ouml");
            Add(result, "×", "times");
            Add(result, "Ø", "Oslash");
            Add(result, "Ù", "Ugrave");
            Add(result, "Ú", "Uacute");
            Add(result, "Û", "Ucirc");
            Add(result, "Ü", "Uuml");
            Add(result, "Ý", "Yacute");
            Add(result, "Þ", "THORN");
            Add(result, "ß", "szlig");
            Add(result, "à", "agrave");
            Add(result, "á", "aacute");
            Add(result, "â", "acirc");
            Add(result, "ã", "atilde");
            Add(result, "ä", "auml");
            Add(result, "å", "aring");
            Add(result, "æ", "aelig");
            Add(result, "ç", "ccedil");
            Add(result, "è", "egrave");
            Add(result, "é", "eacute");
            Add(result, "ê", "ecirc");
            Add(result, "ë", "euml");
            Add(result, "ì", "igrave");
            Add(result, "í", "iacute");
            Add(result, "î", "icirc");
            Add(result, "ï", "iuml");
            Add(result, "ð", "eth");
            Add(result, "ñ", "ntilde");
            Add(result, "ò", "ograve");
            Add(result, "ó", "oacute");
            Add(result, "ô", "ocirc");
            Add(result, "õ", "otilde");
            Add(result, "ö", "ouml");
            Add(result, "÷", "divide", "div");
            Add(result, "ø", "oslash");
            Add(result, "ù", "ugrave");
            Add(result, "ú", "uacute");
            Add(result, "û", "ucirc");
            Add(result, "ü", "uuml");
            Add(result, "ý", "yacute");
            Add(result, "þ", "thorn");
            Add(result, "ÿ", "yuml");
            Add(result, "Ā", "Amacr");
            Add(result, "ā", "amacr");
            Add(result, "Ă", "Abreve");
            Add(result, "ă", "abreve");
            Add(result, "Ą", "Aogon");
            Add(result, "ą", "aogon");
            Add(result, "Ć", "Cacute");
            Add(result, "ć", "cacute");
            Add(result, "Ĉ", "Ccirc");
            Add(result, "ĉ", "ccirc");
            Add(result, "Ċ", "Cdot");
            Add(result, "ċ", "cdot");
            Add(result, "Č", "Ccaron");
            Add(result, "č", "ccaron");
            Add(result, "Ď", "Dcaron");
            Add(result, "ď", "dcaron");
            Add(result, "Đ", "Dstrok");
            Add(result, "đ", "dstrok");
            Add(result, "Ē", "Emacr");
            Add(result, "ē", "emacr");
            Add(result, "Ė", "Edot");
            Add(result, "ė", "edot");
            Add(result, "Ę", "Eogon");
            Add(result, "ę", "eogon");
            Add(result, "Ě", "Ecaron");
            Add(result, "ě", "ecaron");
            Add(result, "Ĝ", "Gcirc");
            Add(result, "ĝ", "gcirc");
            Add(result, "Ğ", "Gbreve");
            Add(result, "ğ", "gbreve");
            Add(result, "Ġ", "Gdot");
            Add(result, "ġ", "gdot");
            Add(result, "Ģ", "Gcedil");
            Add(result, "Ĥ", "Hcirc");
            Add(result, "ĥ", "hcirc");
            Add(result, "Ħ", "Hstrok");
            Add(result, "ħ", "hstrok");
            Add(result, "Ĩ", "Itilde");
            Add(result, "ĩ", "itilde");
            Add(result, "Ī", "Imacr");
            Add(result, "ī", "imacr");
            Add(result, "Į", "Iogon");
            Add(result, "į", "iogon");
            Add(result, "İ", "Idot");
            Add(result, "ı", "imath", "inodot");
            Add(result, "Ĳ", "IJlig");
            Add(result, "ĳ", "ijlig");
            Add(result, "Ĵ", "Jcirc");
            Add(result, "ĵ", "jcirc");
            Add(result, "Ķ", "Kcedil");
            Add(result, "ķ", "kcedil");
            Add(result, "ĸ", "kgreen");
            Add(result, "Ĺ", "Lacute");
            Add(result, "ĺ", "lacute");
            Add(result, "Ļ", "Lcedil");
            Add(result, "ļ", "lcedil");
            Add(result, "Ľ", "Lcaron");
            Add(result, "ľ", "lcaron");
            Add(result, "Ŀ", "Lmidot");
            Add(result, "ŀ", "lmidot");
            Add(result, "Ł", "Lstrok");
            Add(result, "ł", "lstrok");
            Add(result, "Ń", "Nacute");
            Add(result, "ń", "nacute");
            Add(result, "Ņ", "Ncedil");
            Add(result, "ņ", "ncedil");
            Add(result, "Ň", "Ncaron");
            Add(result, "ň", "ncaron");
            Add(result, "ŉ", "napos");
            Add(result, "Ŋ", "ENG");
            Add(result, "ŋ", "eng");
            Add(result, "Ō", "Omacr");
            Add(result, "ō", "omacr");
            Add(result, "Ő", "Odblac");
            Add(result, "ő", "odblac");
            Add(result, "Œ", "OElig");
            Add(result, "œ", "oelig");
            Add(result, "Ŕ", "Racute");
            Add(result, "ŕ", "racute");
            Add(result, "Ŗ", "Rcedil");
            Add(result, "ŗ", "rcedil");
            Add(result, "Ř", "Rcaron");
            Add(result, "ř", "rcaron");
            Add(result, "Ś", "Sacute");
            Add(result, "ś", "sacute");
            Add(result, "Ŝ", "Scirc");
            Add(result, "ŝ", "scirc");
            Add(result, "Ş", "Scedil");
            Add(result, "ş", "scedil");
            Add(result, "Š", "Scaron");
            Add(result, "š", "scaron");
            Add(result, "Ţ", "Tcedil");
            Add(result, "ţ", "tcedil");
            Add(result, "Ť", "Tcaron");
            Add(result, "ť", "tcaron");
            Add(result, "Ŧ", "Tstrok");
            Add(result, "ŧ", "tstrok");
            Add(result, "Ũ", "Utilde");
            Add(result, "ũ", "utilde");
            Add(result, "Ū", "Umacr");
            Add(result, "ū", "umacr");
            Add(result, "Ŭ", "Ubreve");
            Add(result, "ŭ", "ubreve");
            Add(result, "Ů", "Uring");
            Add(result, "ů", "uring");
            Add(result, "Ű", "Udblac");
            Add(result, "ű", "udblac");
            Add(result, "Ų", "Uogon");
            Add(result, "ų", "uogon");
            Add(result, "Ŵ", "Wcirc");
            Add(result, "ŵ", "wcirc");
            Add(result, "Ŷ", "Ycirc");
            Add(result, "ŷ", "ycirc");
            Add(result, "Ÿ", "Yuml");
            Add(result, "Ź", "Zacute");
            Add(result, "ź", "zacute");
            Add(result, "Ż", "Zdot");
            Add(result, "ż", "zdot");
            Add(result, "Ž", "Zcaron");
            Add(result, "ž", "zcaron");
            Add(result, "ƒ", "fnof");
            Add(result, "Ƶ", "imped");
            Add(result, "ǵ", "gacute");
            Add(result, "ȷ", "jmath");
            Add(result, "ˆ", "circ");
            Add(result, "ˇ", "caron", "Hacek");
            Add(result, "˘", "breve");
            Add(result, "˙", "dot", "DiacriticalDot");
            Add(result, "˚", "ring");
            Add(result, "˛", "ogon");
            Add(result, "˜", "tilde", "DiacriticalTilde");
            Add(result, "˝", "dblac", "DiacriticalDoubleAcute");
            Add(result, "̑", "DownBreve");
            Add(result, "Α", "Alpha");
            Add(result, "Β", "Beta");
            Add(result, "Γ", "Gamma");
            Add(result, "Δ", "Delta");
            Add(result, "Ε", "Epsilon");
            Add(result, "Ζ", "Zeta");
            Add(result, "Η", "Eta");
            Add(result, "Θ", "Theta");
            Add(result, "Ι", "Iota");
            Add(result, "Κ", "Kappa");
            Add(result, "Λ", "Lambda");
            Add(result, "Μ", "Mu");
            Add(result, "Ν", "Nu");
            Add(result, "Ξ", "Xi");
            Add(result, "Ο", "Omicron");
            Add(result, "Π", "Pi");
            Add(result, "Ρ", "Rho");
            Add(result, "Σ", "Sigma");
            Add(result, "Τ", "Tau");
            Add(result, "Υ", "Upsilon");
            Add(result, "Φ", "Phi");
            Add(result, "Χ", "Chi");
            Add(result, "Ψ", "Psi");
            Add(result, "Ω", "Omega", "ohm");
            Add(result, "α", "alpha");
            Add(result, "β", "beta");
            Add(result, "γ", "gamma");
            Add(result, "δ", "delta");
            Add(result, "ε", "epsi", "epsilon");
            Add(result, "ζ", "zeta");
            Add(result, "η", "eta");
            Add(result, "θ", "theta");
            Add(result, "ι", "iota");
            Add(result, "κ", "kappa");
            Add(result, "λ", "lambda");
            Add(result, "μ", "mu");
            Add(result, "ν", "nu");
            Add(result, "ξ", "xi");
            Add(result, "ο", "omicron");
            Add(result, "π", "pi");
            Add(result, "ρ", "rho");
            Add(result, "ς", "sigmav", "varsigma", "sigmaf");
            Add(result, "σ", "sigma");
            Add(result, "τ", "tau");
            Add(result, "υ", "upsi", "upsilon");
            Add(result, "φ", "phi");
            Add(result, "χ", "chi");
            Add(result, "ψ", "psi");
            Add(result, "ω", "omega");
            Add(result, "ϑ", "thetav", "vartheta", "thetasym");
            Add(result, "ϒ", "Upsi", "upsih");
            Add(result, "ϕ", "straightphi", "phiv", "varphi");
            Add(result, "ϖ", "piv", "varpi");
            Add(result, "Ϝ", "Gammad");
            Add(result, "ϝ", "gammad", "digamma");
            Add(result, "ϰ", "kappav", "varkappa");
            Add(result, "ϱ", "rhov", "varrho");
            Add(result, "ϵ", "epsiv", "varepsilon", "straightepsilon");
            Add(result, "϶", "bepsi", "backepsilon");
            Add(result, "Ё", "IOcy");
            Add(result, "Ђ", "DJcy");
            Add(result, "Ѓ", "GJcy");
            Add(result, "Є", "Jukcy");
            Add(result, "Ѕ", "DScy");
            Add(result, "І", "Iukcy");
            Add(result, "Ї", "YIcy");
            Add(result, "Ј", "Jsercy");
            Add(result, "Љ", "LJcy");
            Add(result, "Њ", "NJcy");
            Add(result, "Ћ", "TSHcy");
            Add(result, "Ќ", "KJcy");
            Add(result, "Ў", "Ubrcy");
            Add(result, "Џ", "DZcy");
            Add(result, "А", "Acy");
            Add(result, "Б", "Bcy");
            Add(result, "В", "Vcy");
            Add(result, "Г", "Gcy");
            Add(result, "Д", "Dcy");
            Add(result, "Е", "IEcy");
            Add(result, "Ж", "ZHcy");
            Add(result, "З", "Zcy");
            Add(result, "И", "Icy");
            Add(result, "Й", "Jcy");
            Add(result, "К", "Kcy");
            Add(result, "Л", "Lcy");
            Add(result, "М", "Mcy");
            Add(result, "Н", "Ncy");
            Add(result, "О", "Ocy");
            Add(result, "П", "Pcy");
            Add(result, "Р", "Rcy");
            Add(result, "С", "Scy");
            Add(result, "Т", "Tcy");
            Add(result, "У", "Ucy");
            Add(result, "Ф", "Fcy");
            Add(result, "Х", "KHcy");
            Add(result, "Ц", "TScy");
            Add(result, "Ч", "CHcy");
            Add(result, "Ш", "SHcy");
            Add(result, "Щ", "SHCHcy");
            Add(result, "Ъ", "HARDcy");
            Add(result, "Ы", "Ycy");
            Add(result, "Ь", "SOFTcy");
            Add(result, "Э", "Ecy");
            Add(result, "Ю", "YUcy");
            Add(result, "Я", "YAcy");
            Add(result, "а", "acy");
            Add(result, "б", "bcy");
            Add(result, "в", "vcy");
            Add(result, "г", "gcy");
            Add(result, "д", "dcy");
            Add(result, "е", "iecy");
            Add(result, "ж", "zhcy");
            Add(result, "з", "zcy");
            Add(result, "и", "icy");
            Add(result, "й", "jcy");
            Add(result, "к", "kcy");
            Add(result, "л", "lcy");
            Add(result, "м", "mcy");
            Add(result, "н", "ncy");
            Add(result, "о", "ocy");
            Add(result, "п", "pcy");
            Add(result, "р", "rcy");
            Add(result, "с", "scy");
            Add(result, "т", "tcy");
            Add(result, "у", "ucy");
            Add(result, "ф", "fcy");
            Add(result, "х", "khcy");
            Add(result, "ц", "tscy");
            Add(result, "ч", "chcy");
            Add(result, "ш", "shcy");
            Add(result, "щ", "shchcy");
            Add(result, "ъ", "hardcy");
            Add(result, "ы", "ycy");
            Add(result, "ь", "softcy");
            Add(result, "э", "ecy");
            Add(result, "ю", "yucy");
            Add(result, "я", "yacy");
            Add(result, "ё", "iocy");
            Add(result, "ђ", "djcy");
            Add(result, "ѓ", "gjcy");
            Add(result, "є", "jukcy");
            Add(result, "ѕ", "dscy");
            Add(result, "і", "iukcy");
            Add(result, "ї", "yicy");
            Add(result, "ј", "jsercy");
            Add(result, "љ", "ljcy");
            Add(result, "њ", "njcy");
            Add(result, "ћ", "tshcy");
            Add(result, "ќ", "kjcy");
            Add(result, "ў", "ubrcy");
            Add(result, "џ", "dzcy");
            Add(result, " ", "ensp");
            Add(result, " ", "emsp");
            Add(result, " ", "emsp13");
            Add(result, " ", "emsp14");
            Add(result, " ", "numsp");
            Add(result, " ", "puncsp");
            Add(result, " ", "thinsp", "ThinSpace");
            Add(result, " ", "hairsp", "VeryThinSpace");
            Add(result, "​", "ZeroWidthSpace", "NegativeVeryThinSpace", "NegativeThinSpace", "NegativeMediumSpace", "NegativeThickSpace");
            Add(result, "‌", "zwnj");
            Add(result, "‍", "zwj");
            Add(result, "‎", "lrm");
            Add(result, "‏", "rlm");
            Add(result, "‐", "hyphen", "dash");
            Add(result, "–", "ndash");
            Add(result, "—", "mdash");
            Add(result, "―", "horbar");
            Add(result, "‖", "Verbar", "Vert");
            Add(result, "‘", "lsquo", "OpenCurlyQuote");
            Add(result, "’", "rsquo", "rsquor", "CloseCurlyQuote");
            Add(result, "‚", "sbquo", "lsquor");
            Add(result, "“", "ldquo", "OpenCurlyDoubleQuote");
            Add(result, "”", "rdquo", "rdquor", "CloseCurlyDoubleQuote");
            Add(result, "„", "bdquo", "ldquor");
            Add(result, "†", "dagger");
            Add(result, "‡", "Dagger", "ddagger");
            Add(result, "•", "bull", "bullet");
            Add(result, "‥", "nldr");
            Add(result, "…", "hellip", "mldr");
            Add(result, "‰", "permil");
            Add(result, "‱", "pertenk");
            Add(result, "′", "prime");
            Add(result, "″", "Prime");
            Add(result, "‴", "tprime");
            Add(result, "‵", "bprime", "backprime");
            Add(result, "‹", "lsaquo");
            Add(result, "›", "rsaquo");
            Add(result, "‾", "oline", "OverBar");
            Add(result, "⁁", "caret");
            Add(result, "⁃", "hybull");
            Add(result, "⁄", "frasl");
            Add(result, "⁏", "bsemi");
            Add(result, "⁗", "qprime");
            Add(result, " ", "MediumSpace");
            Add(result, "€", "euro");
            Add(result, "⃛", "tdot", "TripleDot");
            Add(result, "⃜", "DotDot");
            Add(result, "ℂ", "Copf", "complexes");
            Add(result, "℅", "incare");
            Add(result, "ℊ", "gscr");
            Add(result, "ℋ", "hamilt", "HilbertSpace", "Hscr");
            Add(result, "ℌ", "Hfr", "Poincareplane");
            Add(result, "ℍ", "quaternions", "Hopf");
            Add(result, "ℎ", "planckh");
            Add(result, "ℏ", "planck", "hbar", "plankv", "hslash");
            Add(result, "ℐ", "Iscr", "imagline");
            Add(result, "ℑ", "image", "Im", "imagpart", "Ifr");
            Add(result, "ℒ", "Lscr", "lagran", "Laplacetrf");
            Add(result, "ℓ", "ell");
            Add(result, "ℕ", "Nopf", "naturals");
            Add(result, "№", "numero");
            Add(result, "℗", "copysr");
            Add(result, "℘", "weierp", "wp");
            Add(result, "ℙ", "Popf", "primes");
            Add(result, "ℚ", "rationals", "Qopf");
            Add(result, "ℛ", "Rscr", "realine");
            Add(result, "ℜ", "real", "Re", "realpart", "Rfr");
            Add(result, "ℝ", "reals", "Ropf");
            Add(result, "℞", "rx");
            Add(result, "™", "trade", "TRADE");
            Add(result, "ℤ", "integers", "Zopf");
            Add(result, "℧", "mho");
            Add(result, "ℨ", "Zfr", "zeetrf");
            Add(result, "℩", "iiota");
            Add(result, "ℬ", "bernou", "Bernoullis", "Bscr");
            Add(result, "ℭ", "Cfr", "Cayleys");
            Add(result, "ℯ", "escr");
            Add(result, "ℰ", "Escr", "expectation");
            Add(result, "ℱ", "Fscr", "Fouriertrf");
            Add(result, "ℳ", "phmmat", "Mellintrf", "Mscr");
            Add(result, "ℴ", "order", "orderof", "oscr");
            Add(result, "ℵ", "alefsym", "aleph");
            Add(result, "ℶ", "beth");
            Add(result, "ℷ", "gimel");
            Add(result, "ℸ", "daleth");
            Add(result, "ⅅ", "CapitalDifferentialD", "DD");
            Add(result, "ⅆ", "DifferentialD", "dd");
            Add(result, "ⅇ", "ExponentialE", "exponentiale", "ee");
            Add(result, "ⅈ", "ImaginaryI", "ii");
            Add(result, "⅓", "frac13");
            Add(result, "⅔", "frac23");
            Add(result, "⅕", "frac15");
            Add(result, "⅖", "frac25");
            Add(result, "⅗", "frac35");
            Add(result, "⅘", "frac45");
            Add(result, "⅙", "frac16");
            Add(result, "⅚", "frac56");
            Add(result, "⅛", "frac18");
            Add(result, "⅜", "frac38");
            Add(result, "⅝", "frac58");
            Add(result, "⅞", "frac78");
            Add(result, "←", "larr", "leftarrow", "LeftArrow, slarr", "ShortLeftArrow");
            Add(result, "↑", "uarr", "uparrow", "UpArrow", "ShortUpArrow");
            Add(result, "→", "rarr", "rightarrow", "RightArrow, srarr", "ShortRightArrow");
            Add(result, "↓", "darr", "downarrow", "DownArrow", "ShortDownArrow");
            Add(result, "↔", "harr", "leftrightarrow", "LeftRightArrow");
            Add(result, "↕", "varr", "updownarrow", "UpDownArrow");
            Add(result, "↖", "nwarr", "UpperLeftArrow", "nwarrow");
            Add(result, "↗", "nearr", "UpperRightArrow", "nearrow");
            Add(result, "↘", "searr", "searrow", "LowerRightArrow");
            Add(result, "↙", "swarr", "swarrow", "LowerLeftArrow");
            Add(result, "↚", "nlarr", "nleftarrow");
            Add(result, "↛", "nrarr", "nrightarrow");
            Add(result, "↝", "rarrw", "rightsquigarrow");
            Add(result, "↞", "Larr", "twoheadleftarrow");
            Add(result, "↟", "Uarr");
            Add(result, "↠", "Rarr", "twoheadrightarrow");
            Add(result, "↡", "Darr");
            Add(result, "↢", "larrtl", "leftarrowtail");
            Add(result, "↣", "rarrtl", "rightarrowtail");
            Add(result, "↤", "LeftTeeArrow", "mapstoleft");
            Add(result, "↥", "UpTeeArrow", "mapstoup");
            Add(result, "↦", "map", "RightTeeArrow", "mapsto");
            Add(result, "↧", "DownTeeArrow", "mapstodown");
            Add(result, "↩", "larrhk", "hookleftarrow");
            Add(result, "↪", "rarrhk", "hookrightarrow");
            Add(result, "↫", "larrlp", "looparrowleft");
            Add(result, "↬", "rarrlp", "looparrowright");
            Add(result, "↭", "harrw", "leftrightsquigarrow");
            Add(result, "↮", "nharr", "nleftrightarrow");
            Add(result, "↰", "lsh", "Lsh");
            Add(result, "↱", "rsh", "Rsh");
            Add(result, "↲", "ldsh");
            Add(result, "↳", "rdsh");
            Add(result, "↵", "crarr");
            Add(result, "↶", "cularr", "curvearrowleft");
            Add(result, "↷", "curarr", "curvearrowright");
            Add(result, "↺", "olarr", "circlearrowleft");
            Add(result, "↻", "orarr", "circlearrowright");
            Add(result, "↼", "lharu", "LeftVector", "leftharpoonup");
            Add(result, "↽", "lhard", "leftharpoondown", "DownLeftVector");
            Add(result, "↾", "uharr", "upharpoonright", "RightUpVector");
            Add(result, "↿", "uharl", "upharpoonleft", "LeftUpVector");
            Add(result, "⇀", "rharu", "RightVector", "rightharpoonup");
            Add(result, "⇁", "rhard", "rightharpoondown", "DownRightVector");
            Add(result, "⇂", "dharr", "RightDownVector", "downharpoonright");
            Add(result, "⇃", "dharl", "LeftDownVector", "downharpoonleft");
            Add(result, "⇄", "rlarr", "rightleftarrows", "RightArrowLeftArrow");
            Add(result, "⇅", "udarr", "UpArrowDownArrow");
            Add(result, "⇆", "lrarr", "leftrightarrows", "LeftArrowRightArrow");
            Add(result, "⇇", "llarr", "leftleftarrows");
            Add(result, "⇈", "uuarr", "upuparrows");
            Add(result, "⇉", "rrarr", "rightrightarrows");
            Add(result, "⇊", "ddarr", "downdownarrows");
            Add(result, "⇋", "lrhar", "ReverseEquilibrium", "leftrightharpoons");
            Add(result, "⇌", "rlhar", "rightleftharpoons", "Equilibrium");
            Add(result, "⇍", "nlArr", "nLeftarrow");
            Add(result, "⇎", "nhArr", "nLeftrightarrow");
            Add(result, "⇏", "nrArr", "nRightarrow");
            Add(result, "⇐", "lArr", "Leftarrow", "DoubleLeftArrow");
            Add(result, "⇑", "uArr", "Uparrow", "DoubleUpArrow");
            Add(result, "⇒", "rArr", "Rightarrow", "Implies", "DoubleRightArrow");
            Add(result, "⇓", "dArr", "Downarrow", "DoubleDownArrow");
            Add(result, "⇔", "hArr", "Leftrightarrow", "DoubleLeftRightArrow", "iff");
            Add(result, "⇕", "vArr", "Updownarrow", "DoubleUpDownArrow");
            Add(result, "⇖", "nwArr");
            Add(result, "⇗", "neArr");
            Add(result, "⇘", "seArr");
            Add(result, "⇙", "swArr");
            Add(result, "⇚", "lAarr", "Lleftarrow");
            Add(result, "⇛", "rAarr", "Rrightarrow");
            Add(result, "⇝", "zigrarr");
            Add(result, "⇤", "larrb", "LeftArrowBar");
            Add(result, "⇥", "rarrb", "RightArrowBar");
            Add(result, "⇵", "duarr", "DownArrowUpArrow");
            Add(result, "⇽", "loarr");
            Add(result, "⇾", "roarr");
            Add(result, "⇿", "hoarr");
            Add(result, "∀", "forall", "ForAll");
            Add(result, "∁", "comp", "complement");
            Add(result, "∂", "part", "PartialD");
            Add(result, "∃", "exist", "Exists");
            Add(result, "∄", "nexist", "NotExists", "nexists");
            Add(result, "∅", "empty", "emptyset", "emptyv", "varnothing");
            Add(result, "∇", "nabla", "Del");
            Add(result, "∈", "isin", "isinv", "Element", "in");
            Add(result, "∉", "notin", "NotElement", "notinva");
            Add(result, "∋", "niv", "ReverseElement", "ni", "SuchThat");
            Add(result, "∌", "notni", "notniva", "NotReverseElement");
            Add(result, "∏", "prod", "Product");
            Add(result, "∐", "coprod", "Coproduct");
            Add(result, "∑", "sum", "Sum");
            Add(result, "−", "minus");
            Add(result, "∓", "mnplus", "mp", "MinusPlus");
            Add(result, "∔", "plusdo", "dotplus");
            Add(result, "∖", "setmn", "setminus", "Backslash, ssetmn", "smallsetminus");
            Add(result, "∗", "lowast");
            Add(result, "∘", "compfn", "SmallCircle");
            Add(result, "√", "radic", "Sqrt");
            Add(result, "∝", "prop", "propto", "Proportional, vprop", "varpropto");
            Add(result, "∞", "infin");
            Add(result, "∟", "angrt");
            Add(result, "∠", "ang", "angle");
            Add(result, "∡", "angmsd", "measuredangle");
            Add(result, "∢", "angsph");
            Add(result, "∣", "mid", "VerticalBar", "smid", "shortmid");
            Add(result, "∤", "nmid", "NotVerticalBar", "nsmid", "nshortmid");
            Add(result, "∥", "par", "parallel", "DoubleVerticalBar, spar", "shortparallel");
            Add(result, "∦", "npar", "nparallel", "NotDoubleVerticalBar, nspar", "nshortparallel");
            Add(result, "∧", "and", "wedge");
            Add(result, "∨", "or", "vee");
            Add(result, "∩", "cap");
            Add(result, "∪", "cup");
            Add(result, "∫", "int", "Integral");
            Add(result, "∬", "Int");
            Add(result, "∭", "tint", "iiint");
            Add(result, "∮", "conint", "oint", "ContourIntegral");
            Add(result, "∯", "Conint", "DoubleContourIntegral");
            Add(result, "∰", "Cconint");
            Add(result, "∱", "cwint");
            Add(result, "∲", "cwconint", "ClockwiseContourIntegral");
            Add(result, "∳", "awconint", "CounterClockwiseContourIntegral");
            Add(result, "∴", "there4", "therefore", "Therefore");
            Add(result, "∵", "becaus", "because", "Because");
            Add(result, "∶", "ratio");
            Add(result, "∷", "Colon", "Proportion");
            Add(result, "∸", "minusd", "dotminus");
            Add(result, "∺", "mDDot");
            Add(result, "∻", "homtht");
            Add(result, "∼", "sim", "Tilde", "thksim", "thicksim");
            Add(result, "∽", "bsim", "backsim");
            Add(result, "∾", "ac", "mstpos");
            Add(result, "∿", "acd");
            Add(result, "≀", "wreath", "VerticalTilde", "wr");
            Add(result, "≁", "nsim", "NotTilde");
            Add(result, "≂", "esim", "EqualTilde", "eqsim");
            Add(result, "≃", "sime", "TildeEqual", "simeq");
            Add(result, "≄", "nsime", "nsimeq", "NotTildeEqual");
            Add(result, "≅", "cong", "TildeFullEqual");
            Add(result, "≆", "simne");
            Add(result, "≇", "ncong", "NotTildeFullEqual");
            Add(result, "≈", "asymp", "ap", "TildeTilde, approx, thkap", "thickapprox");
            Add(result, "≉", "nap", "NotTildeTilde", "napprox");
            Add(result, "≊", "ape", "approxeq");
            Add(result, "≋", "apid");
            Add(result, "≌", "bcong", "backcong");
            Add(result, "≍", "asympeq", "CupCap");
            Add(result, "≎", "bump", "HumpDownHump", "Bumpeq");
            Add(result, "≏", "bumpe", "HumpEqual", "bumpeq");
            Add(result, "≐", "esdot", "DotEqual", "doteq");
            Add(result, "≑", "eDot", "doteqdot");
            Add(result, "≒", "efDot", "fallingdotseq");
            Add(result, "≓", "erDot", "risingdotseq");
            Add(result, "≔", "colone", "coloneq", "Assign");
            Add(result, "≕", "ecolon", "eqcolon");
            Add(result, "≖", "ecir", "eqcirc");
            Add(result, "≗", "cire", "circeq");
            Add(result, "≙", "wedgeq");
            Add(result, "≚", "veeeq");
            Add(result, "≜", "trie", "triangleq");
            Add(result, "≟", "equest", "questeq");
            Add(result, "≠", "ne", "NotEqual");
            Add(result, "≡", "equiv", "Congruent");
            Add(result, "≢", "nequiv", "NotCongruent");
            Add(result, "≤", "le", "leq");
            Add(result, "≥", "ge", "GreaterEqual", "geq");
            Add(result, "≦", "lE", "LessFullEqual", "leqq");
            Add(result, "≧", "gE", "GreaterFullEqual", "geqq");
            Add(result, "≨", "lnE", "lneqq");
            Add(result, "≩", "gnE", "gneqq");
            Add(result, "≪", "Lt", "NestedLessLess", "ll");
            Add(result, "≫", "Gt", "NestedGreaterGreater", "gg");
            Add(result, "≬", "twixt", "between");
            Add(result, "≭", "NotCupCap");
            Add(result, "≮", "nlt", "NotLess", "nless");
            Add(result, "≯", "ngt", "NotGreater", "ngtr");
            Add(result, "≰", "nle", "NotLessEqual", "nleq");
            Add(result, "≱", "nge", "NotGreaterEqual", "ngeq");
            Add(result, "≲", "lsim", "LessTilde", "lesssim");
            Add(result, "≳", "gsim", "gtrsim", "GreaterTilde");
            Add(result, "≴", "nlsim", "NotLessTilde");
            Add(result, "≵", "ngsim", "NotGreaterTilde");
            Add(result, "≶", "lg", "lessgtr", "LessGreater");
            Add(result, "≷", "gl", "gtrless", "GreaterLess");
            Add(result, "≸", "ntlg", "NotLessGreater");
            Add(result, "≹", "ntgl", "NotGreaterLess");
            Add(result, "≺", "pr", "Precedes", "prec");
            Add(result, "≻", "sc", "Succeeds", "succ");
            Add(result, "≼", "prcue", "PrecedesSlantEqual", "preccurlyeq");
            Add(result, "≽", "sccue", "SucceedsSlantEqual", "succcurlyeq");
            Add(result, "≾", "prsim", "precsim", "PrecedesTilde");
            Add(result, "≿", "scsim", "succsim", "SucceedsTilde");
            Add(result, "⊀", "npr", "nprec", "NotPrecedes");
            Add(result, "⊁", "nsc", "nsucc", "NotSucceeds");
            Add(result, "⊂", "sub", "subset");
            Add(result, "⊃", "sup", "supset", "Superset");
            Add(result, "⊄", "nsub");
            Add(result, "⊅", "nsup");
            Add(result, "⊆", "sube", "SubsetEqual", "subseteq");
            Add(result, "⊇", "supe", "supseteq", "SupersetEqual");
            Add(result, "⊈", "nsube", "nsubseteq", "NotSubsetEqual");
            Add(result, "⊉", "nsupe", "nsupseteq", "NotSupersetEqual");
            Add(result, "⊊", "subne", "subsetneq");
            Add(result, "⊋", "supne", "supsetneq");
            Add(result, "⊍", "cupdot");
            Add(result, "⊎", "uplus", "UnionPlus");
            Add(result, "⊏", "sqsub", "SquareSubset", "sqsubset");
            Add(result, "⊐", "sqsup", "SquareSuperset", "sqsupset");
            Add(result, "⊑", "sqsube", "SquareSubsetEqual", "sqsubseteq");
            Add(result, "⊒", "sqsupe", "SquareSupersetEqual", "sqsupseteq");
            Add(result, "⊓", "sqcap", "SquareIntersection");
            Add(result, "⊔", "sqcup", "SquareUnion");
            Add(result, "⊕", "oplus", "CirclePlus");
            Add(result, "⊖", "ominus", "CircleMinus");
            Add(result, "⊗", "otimes", "CircleTimes");
            Add(result, "⊘", "osol");
            Add(result, "⊙", "odot", "CircleDot");
            Add(result, "⊚", "ocir", "circledcirc");
            Add(result, "⊛", "oast", "circledast");
            Add(result, "⊝", "odash", "circleddash");
            Add(result, "⊞", "plusb", "boxplus");
            Add(result, "⊟", "minusb", "boxminus");
            Add(result, "⊠", "timesb", "boxtimes");
            Add(result, "⊡", "sdotb", "dotsquare");
            Add(result, "⊢", "vdash", "RightTee");
            Add(result, "⊣", "dashv", "LeftTee");
            Add(result, "⊤", "top", "DownTee");
            Add(result, "⊥", "bottom", "bot", "perp", "UpTee");
            Add(result, "⊧", "models");
            Add(result, "⊨", "vDash", "DoubleRightTee");
            Add(result, "⊩", "Vdash");
            Add(result, "⊪", "Vvdash");
            Add(result, "⊫", "VDash");
            Add(result, "⊬", "nvdash");
            Add(result, "⊭", "nvDash");
            Add(result, "⊮", "nVdash");
            Add(result, "⊯", "nVDash");
            Add(result, "⊰", "prurel");
            Add(result, "⊲", "vltri", "vartriangleleft", "LeftTriangle");
            Add(result, "⊳", "vrtri", "vartriangleright", "RightTriangle");
            Add(result, "⊴", "ltrie", "trianglelefteq", "LeftTriangleEqual");
            Add(result, "⊵", "rtrie", "trianglerighteq", "RightTriangleEqual");
            Add(result, "⊶", "origof");
            Add(result, "⊷", "imof");
            Add(result, "⊸", "mumap", "multimap");
            Add(result, "⊹", "hercon");
            Add(result, "⊺", "intcal", "intercal");
            Add(result, "⊻", "veebar");
            Add(result, "⊽", "barvee");
            Add(result, "⊾", "angrtvb");
            Add(result, "⊿", "lrtri");
            Add(result, "⋀", "xwedge", "Wedge", "bigwedge");
            Add(result, "⋁", "xvee", "Vee", "bigvee");
            Add(result, "⋂", "xcap", "Intersection", "bigcap");
            Add(result, "⋃", "xcup", "Union", "bigcup");
            Add(result, "⋄", "diam", "diamond", "Diamond");
            Add(result, "⋅", "sdot");
            Add(result, "⋆", "sstarf", "Star");
            Add(result, "⋇", "divonx", "divideontimes");
            Add(result, "⋈", "bowtie");
            Add(result, "⋉", "ltimes");
            Add(result, "⋊", "rtimes");
            Add(result, "⋋", "lthree", "leftthreetimes");
            Add(result, "⋌", "rthree", "rightthreetimes");
            Add(result, "⋍", "bsime", "backsimeq");
            Add(result, "⋎", "cuvee", "curlyvee");
            Add(result, "⋏", "cuwed", "curlywedge");
            Add(result, "⋐", "Sub", "Subset");
            Add(result, "⋑", "Sup", "Supset");
            Add(result, "⋒", "Cap");
            Add(result, "⋓", "Cup");
            Add(result, "⋔", "fork", "pitchfork");
            Add(result, "⋕", "epar");
            Add(result, "⋖", "ltdot", "lessdot");
            Add(result, "⋗", "gtdot", "gtrdot");
            Add(result, "⋘", "Ll");
            Add(result, "⋙", "Gg", "ggg");
            Add(result, "⋚", "leg", "LessEqualGreater", "lesseqgtr");
            Add(result, "⋛", "gel", "gtreqless", "GreaterEqualLess");
            Add(result, "⋞", "cuepr", "curlyeqprec");
            Add(result, "⋟", "cuesc", "curlyeqsucc");
            Add(result, "⋠", "nprcue", "NotPrecedesSlantEqual");
            Add(result, "⋡", "nsccue", "NotSucceedsSlantEqual");
            Add(result, "⋢", "nsqsube", "NotSquareSubsetEqual");
            Add(result, "⋣", "nsqsupe", "NotSquareSupersetEqual");
            Add(result, "⋦", "lnsim");
            Add(result, "⋧", "gnsim");
            Add(result, "⋨", "prnsim", "precnsim");
            Add(result, "⋩", "scnsim", "succnsim");
            Add(result, "⋪", "nltri", "ntriangleleft", "NotLeftTriangle");
            Add(result, "⋫", "nrtri", "ntriangleright", "NotRightTriangle");
            Add(result, "⋬", "nltrie", "ntrianglelefteq", "NotLeftTriangleEqual");
            Add(result, "⋭", "nrtrie", "ntrianglerighteq", "NotRightTriangleEqual");
            Add(result, "⋮", "vellip");
            Add(result, "⋯", "ctdot");
            Add(result, "⋰", "utdot");
            Add(result, "⋱", "dtdot");
            Add(result, "⋲", "disin");
            Add(result, "⋳", "isinsv");
            Add(result, "⋴", "isins");
            Add(result, "⋵", "isindot");
            Add(result, "⋶", "notinvc");
            Add(result, "⋷", "notinvb");
            Add(result, "⋹", "isinE");
            Add(result, "⋺", "nisd");
            Add(result, "⋻", "xnis");
            Add(result, "⋼", "nis");
            Add(result, "⋽", "notnivc");
            Add(result, "⋾", "notnivb");
            Add(result, "⌅", "barwed", "barwedge");
            Add(result, "⌆", "Barwed", "doublebarwedge");
            Add(result, "⌈", "lceil", "LeftCeiling");
            Add(result, "⌉", "rceil", "RightCeiling");
            Add(result, "⌊", "lfloor", "LeftFloor");
            Add(result, "⌋", "rfloor", "RightFloor");
            Add(result, "⌌", "drcrop");
            Add(result, "⌍", "dlcrop");
            Add(result, "⌎", "urcrop");
            Add(result, "⌏", "ulcrop");
            Add(result, "⌐", "bnot");
            Add(result, "⌒", "profline");
            Add(result, "⌓", "profsurf");
            Add(result, "⌕", "telrec");
            Add(result, "⌖", "target");
            Add(result, "⌜", "ulcorn", "ulcorner");
            Add(result, "⌝", "urcorn", "urcorner");
            Add(result, "⌞", "dlcorn", "llcorner");
            Add(result, "⌟", "drcorn", "lrcorner");
            Add(result, "⌢", "frown", "sfrown");
            Add(result, "⌣", "smile", "ssmile");
            Add(result, "⌭", "cylcty");
            Add(result, "⌮", "profalar");
            Add(result, "⌶", "topbot");
            Add(result, "⌽", "ovbar");
            Add(result, "⌿", "solbar");
            Add(result, "⍼", "angzarr");
            Add(result, "⎰", "lmoust", "lmoustache");
            Add(result, "⎱", "rmoust", "rmoustache");
            Add(result, "⎴", "tbrk", "OverBracket");
            Add(result, "⎵", "bbrk", "UnderBracket");
            Add(result, "⎶", "bbrktbrk");
            Add(result, "⏜", "OverParenthesis");
            Add(result, "⏝", "UnderParenthesis");
            Add(result, "⏞", "OverBrace");
            Add(result, "⏟", "UnderBrace");
            Add(result, "⏢", "trpezium");
            Add(result, "⏧", "elinters");
            Add(result, "␣", "blank");
            Add(result, "Ⓢ", "oS", "circledS");
            Add(result, "─", "boxh", "HorizontalLine");
            Add(result, "│", "boxv");
            Add(result, "┌", "boxdr");
            Add(result, "┐", "boxdl");
            Add(result, "└", "boxur");
            Add(result, "┘", "boxul");
            Add(result, "├", "boxvr");
            Add(result, "┤", "boxvl");
            Add(result, "┬", "boxhd");
            Add(result, "┴", "boxhu");
            Add(result, "┼", "boxvh");
            Add(result, "═", "boxH");
            Add(result, "║", "boxV");
            Add(result, "╒", "boxdR");
            Add(result, "╓", "boxDr");
            Add(result, "╔", "boxDR");
            Add(result, "╕", "boxdL");
            Add(result, "╖", "boxDl");
            Add(result, "╗", "boxDL");
            Add(result, "╘", "boxuR");
            Add(result, "╙", "boxUr");
            Add(result, "╚", "boxUR");
            Add(result, "╛", "boxuL");
            Add(result, "╜", "boxUl");
            Add(result, "╝", "boxUL");
            Add(result, "╞", "boxvR");
            Add(result, "╟", "boxVr");
            Add(result, "╠", "boxVR");
            Add(result, "╡", "boxvL");
            Add(result, "╢", "boxVl");
            Add(result, "╣", "boxVL");
            Add(result, "╤", "boxHd");
            Add(result, "╥", "boxhD");
            Add(result, "╦", "boxHD");
            Add(result, "╧", "boxHu");
            Add(result, "╨", "boxhU");
            Add(result, "╩", "boxHU");
            Add(result, "╪", "boxvH");
            Add(result, "╫", "boxVh");
            Add(result, "╬", "boxVH");
            Add(result, "▀", "uhblk");
            Add(result, "▄", "lhblk");
            Add(result, "█", "block");
            Add(result, "░", "blk14");
            Add(result, "▒", "blk12");
            Add(result, "▓", "blk34");
            Add(result, "□", "squ", "square", "Square");
            Add(result, "▪", "squf", "squarf", "blacksquare", "FilledVerySmallSquare");
            Add(result, "▫", "EmptyVerySmallSquare");
            Add(result, "▭", "rect");
            Add(result, "▮", "marker");
            Add(result, "▱", "fltns");
            Add(result, "△", "xutri", "bigtriangleup");
            Add(result, "▴", "utrif", "blacktriangle");
            Add(result, "▵", "utri", "triangle");
            Add(result, "▸", "rtrif", "blacktriangleright");
            Add(result, "▹", "rtri", "triangleright");
            Add(result, "▽", "xdtri", "bigtriangledown");
            Add(result, "▾", "dtrif", "blacktriangledown");
            Add(result, "▿", "dtri", "triangledown");
            Add(result, "◂", "ltrif", "blacktriangleleft");
            Add(result, "◃", "ltri", "triangleleft");
            Add(result, "◊", "loz", "lozenge");
            Add(result, "○", "cir");
            Add(result, "◬", "tridot");
            Add(result, "◯", "xcirc", "bigcirc");
            Add(result, "◸", "ultri");
            Add(result, "◹", "urtri");
            Add(result, "◺", "lltri");
            Add(result, "◻", "EmptySmallSquare");
            Add(result, "◼", "FilledSmallSquare");
            Add(result, "★", "starf", "bigstar");
            Add(result, "☆", "star");
            Add(result, "☎", "phone");
            Add(result, "♀", "female");
            Add(result, "♂", "male");
            Add(result, "♠", "spades", "spadesuit");
            Add(result, "♣", "clubs", "clubsuit");
            Add(result, "♥", "hearts", "heartsuit");
            Add(result, "♦", "diams", "diamondsuit");
            Add(result, "♪", "sung");
            Add(result, "♭", "flat");
            Add(result, "♮", "natur", "natural");
            Add(result, "♯", "sharp");
            Add(result, "✓", "check", "checkmark");
            Add(result, "✗", "cross");
            Add(result, "✠", "malt", "maltese");
            Add(result, "✶", "sext");
            Add(result, "❘", "VerticalSeparator");
            Add(result, "❲", "lbbrk");
            Add(result, "❳", "rbbrk");
            Add(result, "⟈", "bsolhsub");
            Add(result, "⟉", "suphsol");
            Add(result, "⟦", "lobrk", "LeftDoubleBracket");
            Add(result, "⟧", "robrk", "RightDoubleBracket");
            Add(result, "⟨", "lang", "LeftAngleBracket", "langle");
            Add(result, "⟩", "rang", "RightAngleBracket", "rangle");
            Add(result, "⟪", "Lang");
            Add(result, "⟫", "Rang");
            Add(result, "⟬", "loang");
            Add(result, "⟭", "roang");
            Add(result, "⟵", "xlarr", "longleftarrow", "LongLeftArrow");
            Add(result, "⟶", "xrarr", "longrightarrow", "LongRightArrow");
            Add(result, "⟷", "xharr", "longleftrightarrow", "LongLeftRightArrow");
            Add(result, "⟸", "xlArr", "Longleftarrow", "DoubleLongLeftArrow");
            Add(result, "⟹", "xrArr", "Longrightarrow", "DoubleLongRightArrow");
            Add(result, "⟺", "xhArr", "Longleftrightarrow", "DoubleLongLeftRightArrow");
            Add(result, "⟼", "xmap", "longmapsto");
            Add(result, "⟿", "dzigrarr");
            Add(result, "⤂", "nvlArr");
            Add(result, "⤃", "nvrArr");
            Add(result, "⤄", "nvHarr");
            Add(result, "⤅", "Map");
            Add(result, "⤌", "lbarr");
            Add(result, "⤍", "rbarr", "bkarow");
            Add(result, "⤎", "lBarr");
            Add(result, "⤏", "rBarr", "dbkarow");
            Add(result, "⤐", "RBarr", "drbkarow");
            Add(result, "⤑", "DDotrahd");
            Add(result, "⤒", "UpArrowBar");
            Add(result, "⤓", "DownArrowBar");
            Add(result, "⤖", "Rarrtl");
            Add(result, "⤙", "latail");
            Add(result, "⤚", "ratail");
            Add(result, "⤛", "lAtail");
            Add(result, "⤜", "rAtail");
            Add(result, "⤝", "larrfs");
            Add(result, "⤞", "rarrfs");
            Add(result, "⤟", "larrbfs");
            Add(result, "⤠", "rarrbfs");
            Add(result, "⤣", "nwarhk");
            Add(result, "⤤", "nearhk");
            Add(result, "⤥", "searhk", "hksearow");
            Add(result, "⤦", "swarhk", "hkswarow");
            Add(result, "⤧", "nwnear");
            Add(result, "⤨", "nesear", "toea");
            Add(result, "⤩", "seswar", "tosa");
            Add(result, "⤪", "swnwar");
            Add(result, "⤳", "rarrc");
            Add(result, "⤵", "cudarrr");
            Add(result, "⤶", "ldca");
            Add(result, "⤷", "rdca");
            Add(result, "⤸", "cudarrl");
            Add(result, "⤹", "larrpl");
            Add(result, "⤼", "curarrm");
            Add(result, "⤽", "cularrp");
            Add(result, "⥅", "rarrpl");
            Add(result, "⥈", "harrcir");
            Add(result, "⥉", "Uarrocir");
            Add(result, "⥊", "lurdshar");
            Add(result, "⥋", "ldrushar");
            Add(result, "⥎", "LeftRightVector");
            Add(result, "⥏", "RightUpDownVector");
            Add(result, "⥐", "DownLeftRightVector");
            Add(result, "⥑", "LeftUpDownVector");
            Add(result, "⥒", "LeftVectorBar");
            Add(result, "⥓", "RightVectorBar");
            Add(result, "⥔", "RightUpVectorBar");
            Add(result, "⥕", "RightDownVectorBar");
            Add(result, "⥖", "DownLeftVectorBar");
            Add(result, "⥗", "DownRightVectorBar");
            Add(result, "⥘", "LeftUpVectorBar");
            Add(result, "⥙", "LeftDownVectorBar");
            Add(result, "⥚", "LeftTeeVector");
            Add(result, "⥛", "RightTeeVector");
            Add(result, "⥜", "RightUpTeeVector");
            Add(result, "⥝", "RightDownTeeVector");
            Add(result, "⥞", "DownLeftTeeVector");
            Add(result, "⥟", "DownRightTeeVector");
            Add(result, "⥠", "LeftUpTeeVector");
            Add(result, "⥡", "LeftDownTeeVector");
            Add(result, "⥢", "lHar");
            Add(result, "⥣", "uHar");
            Add(result, "⥤", "rHar");
            Add(result, "⥥", "dHar");
            Add(result, "⥦", "luruhar");
            Add(result, "⥧", "ldrdhar");
            Add(result, "⥨", "ruluhar");
            Add(result, "⥩", "rdldhar");
            Add(result, "⥪", "lharul");
            Add(result, "⥫", "llhard");
            Add(result, "⥬", "rharul");
            Add(result, "⥭", "lrhard");
            Add(result, "⥮", "udhar", "UpEquilibrium");
            Add(result, "⥯", "duhar", "ReverseUpEquilibrium");
            Add(result, "⥰", "RoundImplies");
            Add(result, "⥱", "erarr");
            Add(result, "⥲", "simrarr");
            Add(result, "⥳", "larrsim");
            Add(result, "⥴", "rarrsim");
            Add(result, "⥵", "rarrap");
            Add(result, "⥶", "ltlarr");
            Add(result, "⥸", "gtrarr");
            Add(result, "⥹", "subrarr");
            Add(result, "⥻", "suplarr");
            Add(result, "⥼", "lfisht");
            Add(result, "⥽", "rfisht");
            Add(result, "⥾", "ufisht");
            Add(result, "⥿", "dfisht");
            Add(result, "⦅", "lopar");
            Add(result, "⦆", "ropar");
            Add(result, "⦋", "lbrke");
            Add(result, "⦌", "rbrke");
            Add(result, "⦍", "lbrkslu");
            Add(result, "⦎", "rbrksld");
            Add(result, "⦏", "lbrksld");
            Add(result, "⦐", "rbrkslu");
            Add(result, "⦑", "langd");
            Add(result, "⦒", "rangd");
            Add(result, "⦓", "lparlt");
            Add(result, "⦔", "rpargt");
            Add(result, "⦕", "gtlPar");
            Add(result, "⦖", "ltrPar");
            Add(result, "⦚", "vzigzag");
            Add(result, "⦜", "vangrt");
            Add(result, "⦝", "angrtvbd");
            Add(result, "⦤", "ange");
            Add(result, "⦥", "range");
            Add(result, "⦦", "dwangle");
            Add(result, "⦧", "uwangle");
            Add(result, "⦨", "angmsdaa");
            Add(result, "⦩", "angmsdab");
            Add(result, "⦪", "angmsdac");
            Add(result, "⦫", "angmsdad");
            Add(result, "⦬", "angmsdae");
            Add(result, "⦭", "angmsdaf");
            Add(result, "⦮", "angmsdag");
            Add(result, "⦯", "angmsdah");
            Add(result, "⦰", "bemptyv");
            Add(result, "⦱", "demptyv");
            Add(result, "⦲", "cemptyv");
            Add(result, "⦳", "raemptyv");
            Add(result, "⦴", "laemptyv");
            Add(result, "⦵", "ohbar");
            Add(result, "⦶", "omid");
            Add(result, "⦷", "opar");
            Add(result, "⦹", "operp");
            Add(result, "⦻", "olcross");
            Add(result, "⦼", "odsold");
            Add(result, "⦾", "olcir");
            Add(result, "⦿", "ofcir");
            Add(result, "⧀", "olt");
            Add(result, "⧁", "ogt");
            Add(result, "⧂", "cirscir");
            Add(result, "⧃", "cirE");
            Add(result, "⧄", "solb");
            Add(result, "⧅", "bsolb");
            Add(result, "⧉", "boxbox");
            Add(result, "⧍", "trisb");
            Add(result, "⧎", "rtriltri");
            Add(result, "⧏", "LeftTriangleBar");
            Add(result, "⧐", "RightTriangleBar");
            Add(result, "⧜", "iinfin");
            Add(result, "⧝", "infintie");
            Add(result, "⧞", "nvinfin");
            Add(result, "⧣", "eparsl");
            Add(result, "⧤", "smeparsl");
            Add(result, "⧥", "eqvparsl");
            Add(result, "⧫", "lozf", "blacklozenge");
            Add(result, "⧴", "RuleDelayed");
            Add(result, "⧶", "dsol");
            Add(result, "⨀", "xodot", "bigodot");
            Add(result, "⨁", "xoplus", "bigoplus");
            Add(result, "⨂", "xotime", "bigotimes");
            Add(result, "⨄", "xuplus", "biguplus");
            Add(result, "⨆", "xsqcup", "bigsqcup");
            Add(result, "⨌", "qint", "iiiint");
            Add(result, "⨍", "fpartint");
            Add(result, "⨐", "cirfnint");
            Add(result, "⨑", "awint");
            Add(result, "⨒", "rppolint");
            Add(result, "⨓", "scpolint");
            Add(result, "⨔", "npolint");
            Add(result, "⨕", "pointint");
            Add(result, "⨖", "quatint");
            Add(result, "⨗", "intlarhk");
            Add(result, "⨢", "pluscir");
            Add(result, "⨣", "plusacir");
            Add(result, "⨤", "simplus");
            Add(result, "⨥", "plusdu");
            Add(result, "⨦", "plussim");
            Add(result, "⨧", "plustwo");
            Add(result, "⨩", "mcomma");
            Add(result, "⨪", "minusdu");
            Add(result, "⨭", "loplus");
            Add(result, "⨮", "roplus");
            Add(result, "⨯", "Cross");
            Add(result, "⨰", "timesd");
            Add(result, "⨱", "timesbar");
            Add(result, "⨳", "smashp");
            Add(result, "⨴", "lotimes");
            Add(result, "⨵", "rotimes");
            Add(result, "⨶", "otimesas");
            Add(result, "⨷", "Otimes");
            Add(result, "⨸", "odiv");
            Add(result, "⨹", "triplus");
            Add(result, "⨺", "triminus");
            Add(result, "⨻", "tritime");
            Add(result, "⨼", "iprod", "intprod");
            Add(result, "⨿", "amalg");
            Add(result, "⩀", "capdot");
            Add(result, "⩂", "ncup");
            Add(result, "⩃", "ncap");
            Add(result, "⩄", "capand");
            Add(result, "⩅", "cupor");
            Add(result, "⩆", "cupcap");
            Add(result, "⩇", "capcup");
            Add(result, "⩈", "cupbrcap");
            Add(result, "⩉", "capbrcup");
            Add(result, "⩊", "cupcup");
            Add(result, "⩋", "capcap");
            Add(result, "⩌", "ccups");
            Add(result, "⩍", "ccaps");
            Add(result, "⩐", "ccupssm");
            Add(result, "⩓", "And");
            Add(result, "⩔", "Or");
            Add(result, "⩕", "andand");
            Add(result, "⩖", "oror");
            Add(result, "⩗", "orslope");
            Add(result, "⩘", "andslope");
            Add(result, "⩚", "andv");
            Add(result, "⩛", "orv");
            Add(result, "⩜", "andd");
            Add(result, "⩝", "ord");
            Add(result, "⩟", "wedbar");
            Add(result, "⩦", "sdote");
            Add(result, "⩪", "simdot");
            Add(result, "⩭", "congdot");
            Add(result, "⩮", "easter");
            Add(result, "⩯", "apacir");
            Add(result, "⩰", "apE");
            Add(result, "⩱", "eplus");
            Add(result, "⩲", "pluse");
            Add(result, "⩳", "Esim");
            Add(result, "⩴", "Colone");
            Add(result, "⩵", "Equal");
            Add(result, "⩷", "eDDot", "ddotseq");
            Add(result, "⩸", "equivDD");
            Add(result, "⩹", "ltcir");
            Add(result, "⩺", "gtcir");
            Add(result, "⩻", "ltquest");
            Add(result, "⩼", "gtquest");
            Add(result, "⩽", "les", "LessSlantEqual", "leqslant");
            Add(result, "⩾", "ges", "GreaterSlantEqual", "geqslant");
            Add(result, "⩿", "lesdot");
            Add(result, "⪀", "gesdot");
            Add(result, "⪁", "lesdoto");
            Add(result, "⪂", "gesdoto");
            Add(result, "⪃", "lesdotor");
            Add(result, "⪄", "gesdotol");
            Add(result, "⪅", "lap", "lessapprox");
            Add(result, "⪆", "gap", "gtrapprox");
            Add(result, "⪇", "lne", "lneq");
            Add(result, "⪈", "gne", "gneq");
            Add(result, "⪉", "lnap", "lnapprox");
            Add(result, "⪊", "gnap", "gnapprox");
            Add(result, "⪋", "lEg", "lesseqqgtr");
            Add(result, "⪌", "gEl", "gtreqqless");
            Add(result, "⪍", "lsime");
            Add(result, "⪎", "gsime");
            Add(result, "⪏", "lsimg");
            Add(result, "⪐", "gsiml");
            Add(result, "⪑", "lgE");
            Add(result, "⪒", "glE");
            Add(result, "⪓", "lesges");
            Add(result, "⪔", "gesles");
            Add(result, "⪕", "els", "eqslantless");
            Add(result, "⪖", "egs", "eqslantgtr");
            Add(result, "⪗", "elsdot");
            Add(result, "⪘", "egsdot");
            Add(result, "⪙", "el");
            Add(result, "⪚", "eg");
            Add(result, "⪝", "siml");
            Add(result, "⪞", "simg");
            Add(result, "⪟", "simlE");
            Add(result, "⪠", "simgE");
            Add(result, "⪡", "LessLess");
            Add(result, "⪢", "GreaterGreater");
            Add(result, "⪤", "glj");
            Add(result, "⪥", "gla");
            Add(result, "⪦", "ltcc");
            Add(result, "⪧", "gtcc");
            Add(result, "⪨", "lescc");
            Add(result, "⪩", "gescc");
            Add(result, "⪪", "smt");
            Add(result, "⪫", "lat");
            Add(result, "⪬", "smte");
            Add(result, "⪭", "late");
            Add(result, "⪮", "bumpE");
            Add(result, "⪯", "pre", "preceq", "PrecedesEqual");
            Add(result, "⪰", "sce", "succeq", "SucceedsEqual");
            Add(result, "⪳", "prE");
            Add(result, "⪴", "scE");
            Add(result, "⪵", "prnE", "precneqq");
            Add(result, "⪶", "scnE", "succneqq");
            Add(result, "⪷", "prap", "precapprox");
            Add(result, "⪸", "scap", "succapprox");
            Add(result, "⪹", "prnap", "precnapprox");
            Add(result, "⪺", "scnap", "succnapprox");
            Add(result, "⪻", "Pr");
            Add(result, "⪼", "Sc");
            Add(result, "⪽", "subdot");
            Add(result, "⪾", "supdot");
            Add(result, "⪿", "subplus");
            Add(result, "⫀", "supplus");
            Add(result, "⫁", "submult");
            Add(result, "⫂", "supmult");
            Add(result, "⫃", "subedot");
            Add(result, "⫄", "supedot");
            Add(result, "⫅", "subE", "subseteqq");
            Add(result, "⫆", "supE", "supseteqq");
            Add(result, "⫇", "subsim");
            Add(result, "⫈", "supsim");
            Add(result, "⫋", "subnE", "subsetneqq");
            Add(result, "⫌", "supnE", "supsetneqq");
            Add(result, "⫏", "csub");
            Add(result, "⫐", "csup");
            Add(result, "⫑", "csube");
            Add(result, "⫒", "csupe");
            Add(result, "⫓", "subsup");
            Add(result, "⫔", "supsub");
            Add(result, "⫕", "subsub");
            Add(result, "⫖", "supsup");
            Add(result, "⫗", "suphsub");
            Add(result, "⫘", "supdsub");
            Add(result, "⫙", "forkv");
            Add(result, "⫚", "topfork");
            Add(result, "⫛", "mlcp");
            Add(result, "⫤", "Dashv", "DoubleLeftTee");
            Add(result, "⫦", "Vdashl");
            Add(result, "⫧", "Barv");
            Add(result, "⫨", "vBar");
            Add(result, "⫩", "vBarv");
            Add(result, "⫫", "Vbar");
            Add(result, "⫬", "Not");
            Add(result, "⫭", "bNot");
            Add(result, "⫮", "rnmid");
            Add(result, "⫯", "cirmid");
            Add(result, "⫰", "midcir");
            Add(result, "⫱", "topcir");
            Add(result, "⫲", "nhpar");
            Add(result, "⫳", "parsim");
            Add(result, "⫽", "parsl");
            Add(result, "ﬀ", "fflig");
            Add(result, "ﬁ", "filig");
            Add(result, "ﬂ", "fllig");
            Add(result, "ﬃ", "ffilig");
            Add(result, "ﬄ", "ffllig");
            Add(result, "⃒", "nvlt");
            Add(result, "⃥", "bne");
            Add(result, "⃒", "nvgt");
            Add(result, "j", "fjlig");
            Add(result, " ", "ThickSpace");
            Add(result, "̸", "nrarrw");
            Add(result, "̸", "npart");
            Add(result, "⃒", "nang");
            Add(result, "︀", "caps");
            Add(result, "︀", "cups");
            Add(result, "⃒", "nvsim");
            Add(result, "̱", "race");
            Add(result, "̳", "acE");
            Add(result, "̸", "nesim");
            Add(result, "̸", "napid");
            Add(result, "⃒", "nvap");
            Add(result, "̸", "nbump");
            Add(result, "̸", "nbumpe");
            Add(result, "̸", "nedot");
            Add(result, "⃥", "bnequiv");
            Add(result, "⃒", "nvle");
            Add(result, "⃒", "nvge");
            Add(result, "̸", "nlE");
            Add(result, "̸", "ngE", "ngeqq");
            Add(result, "︀", "lvertneqq");
            Add(result, "︀", "gvertneqq");
            Add(result, "̸", "nLtv");
            Add(result, "⃒", "nLt");
            Add(result, "̸", "nGtv");
            Add(result, "⃒", "nGt");
            Add(result, "̸", "NotSucceedsTilde");
            Add(result, "⃒", "NotSubset", "nsubset");
            Add(result, "⃒", "NotSuperset", "nsupset");
            Add(result, "︀", "varsubsetneq");
            Add(result, "︀", "varsupsetneq");
            Add(result, "̸", "NotSquareSubset");
            Add(result, "̸", "NotSquareSuperset");
            Add(result, "︀", "sqcaps");
            Add(result, "︀", "sqcups");
            Add(result, "⃒", "nvltrie");
            Add(result, "⃒", "nvrtrie");
            Add(result, "̸", "nLl");
            Add(result, "̸", "nGg");
            Add(result, "︀", "lesg");
            Add(result, "︀", "gesl");
            Add(result, "̸", "notindot");
            Add(result, "̸", "notinE");
            Add(result, "̸", "nrarrc");
            Add(result, "̸", "NotLeftTriangleBar");
            Add(result, "̸", "NotRightTriangleBar");
            Add(result, "̸", "ncongdot");
            Add(result, "̸", "napE");
            Add(result, "̸", "nleqslant", "nles");
            Add(result, "̸", "ngeqslant", "nges");
            Add(result, "̸", "NotNestedLessLess");
            Add(result, "̸", "NotNestedGreaterGreater");
            Add(result, "︀", "smtes");
            Add(result, "︀", "lates");
            Add(result, "̸", "NotPrecedesEqual", "npre");
            Add(result, "̸", "NotSucceedsEqual", "nsce");
            Add(result, "̸", "nsubE");
            Add(result, "̸", "nsupE");
            Add(result, "︀", "varsubsetneqq");
            Add(result, "︀", "varsupsetneqq");
            return result;
        }

        /// <summary>
        ///     decode a entity
        /// </summary>
        /// <param name="entityName"></param>
        /// <returns></returns>
        internal static string Decode(string entityName) {
            if (!values.Value.lookup.TryGetValue(entityName, out var result)) {
                result = string.Empty;
            }
            return result;
        }
    }
}
